# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Prepare environment
description: Install dependencies and prepare environment

inputs:
  verilator-version:
    description: Verilator version to install
    required: true
    default: '4.210'
  verilator-path:
    description: Path at which to install Veriltator
    required: true
    default: /tools/verilator

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        version: '0.6.1'
        enable-cache: true
        cache-dependency-glob: |
          python-requirements.txt

    - name: Install Python
      shell: bash
      run: |
        uv python install 3.10
        # Create a virtual environment for UV
        uv venv ~/.local/share/venv
        echo "$HOME/.local/share/venv/bin" >> "$GITHUB_PATH"
        echo "VIRTUAL_ENV=$HOME/.local/share/venv" >> "$GITHUB_ENV"

    - name: Install Python dependencies
      shell: bash
      run: |
        uv pip install -r python-requirements.txt

    - name: Install Verilator
      run: |
        VERILATOR_TAR="verilator-v${{ inputs.verilator-version }}.tar.gz"
        VERILATOR_URL="https://storage.googleapis.com/verilator-builds/${VERILATOR_TAR}"
        sudo mkdir -p "${{ inputs.verilator-path }}"
        curl -sSfL "$VERILATOR_URL" | sudo tar -C "${{ inputs.verilator-path }}" -xvzf -
        echo "${{ inputs.verilator-path }}/v${{ inputs.verilator-version }}/bin" >> "$GITHUB_PATH"
      shell: bash
