# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

RISCV_TOOLS    ?=
OUTFILE 			 ?= hello
PROGRAM_CFLAGS ?=
PROGRAM_INCS 	 ?=
PROGRAM_LIBS 	 ?=
PROGRAM_SRCS   ?= main.c

COMMON_DIR     ?= ../baremetal
include ${COMMON_DIR}/common.mk
